/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventana;

import Gestion.GestionCategorias;
import Gestion.GestionProductos;
import Gestion.GestionTablas;
import Modelo.Producto;
import static Ventana.VentanaPrincipal.panelTareas;
import java.awt.BorderLayout;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Jose Miguel
 */
public class PanelProductos extends javax.swing.JPanel {
    private VentanaPrincipal ventanaPrincipal;
    /**
     * Creates new form PanelProductos
     */
    public PanelProductos() {
        initComponents();
        GestionTablas tablas = new GestionTablas();
        GestionProductos productosTotal = new GestionProductos();
        List <Producto>listaProductosT = new ArrayList<Producto>();
        listaProductosT =  productosTotal.consularProductos();
        tablaProductos.setModel(tablas.crearTablaProductos(listaProductosT));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spTablaProductos = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        panelBotonInsertarNuevoP = new javax.swing.JPanel();
        botonInsertarNuevoP = new javax.swing.JLabel();
        panelBotonModificarP = new javax.swing.JPanel();
        botonModificarProducto = new javax.swing.JLabel();
        panelBotonEliminarP = new javax.swing.JPanel();
        botonEliminarProducto = new javax.swing.JLabel();
        tfBuscarProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panelBotonBuscarP = new javax.swing.JPanel();
        botonBuscarProducto = new javax.swing.JLabel();
        panelVerCategorias = new javax.swing.JPanel();
        botonVerCategorias = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spTablaProductos.setViewportView(tablaProductos);

        add(spTablaProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 860, 430));

        panelBotonInsertarNuevoP.setBackground(new java.awt.Color(255, 255, 255));
        panelBotonInsertarNuevoP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonInsertarNuevoP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonInsertarNuevoP.setForeground(new java.awt.Color(60, 89, 221));
        botonInsertarNuevoP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonInsertarNuevoP.setText("Insertar producto");
        botonInsertarNuevoP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInsertarNuevoPMouseClicked(evt);
            }
        });
        panelBotonInsertarNuevoP.add(botonInsertarNuevoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        add(panelBotonInsertarNuevoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 160, 40));

        panelBotonModificarP.setBackground(new java.awt.Color(255, 255, 255));
        panelBotonModificarP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonModificarProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonModificarProducto.setForeground(new java.awt.Color(60, 89, 221));
        botonModificarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonModificarProducto.setText("Modificar producto");
        botonModificarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonModificarProductoMouseClicked(evt);
            }
        });
        panelBotonModificarP.add(botonModificarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        add(panelBotonModificarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 160, 40));

        panelBotonEliminarP.setBackground(new java.awt.Color(255, 255, 255));
        panelBotonEliminarP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonEliminarProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonEliminarProducto.setForeground(new java.awt.Color(60, 89, 221));
        botonEliminarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonEliminarProducto.setText("Eliminar Producto");
        botonEliminarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEliminarProductoMouseClicked(evt);
            }
        });
        panelBotonEliminarP.add(botonEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        add(panelBotonEliminarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, 160, 40));
        add(tfBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 740, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 89, 221));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Productos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 60));

        panelBotonBuscarP.setBackground(new java.awt.Color(255, 255, 255));
        panelBotonBuscarP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonBuscarProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonBuscarProducto.setForeground(new java.awt.Color(60, 89, 221));
        botonBuscarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonBuscarProducto.setText("Buscar");
        botonBuscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBuscarProductoMouseClicked(evt);
            }
        });
        panelBotonBuscarP.add(botonBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        add(panelBotonBuscarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 60, 30));

        panelVerCategorias.setBackground(new java.awt.Color(255, 255, 255));
        panelVerCategorias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonVerCategorias.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonVerCategorias.setForeground(new java.awt.Color(60, 89, 221));
        botonVerCategorias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonVerCategorias.setText("Ver Categorias");
        botonVerCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVerCategoriasMouseClicked(evt);
            }
        });
        panelVerCategorias.add(botonVerCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        add(panelVerCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, 90, 30));
    }// </editor-fold>//GEN-END:initComponents
/**
 * Método para insertar un nuevo producto.
 * @param evt 
 */
    private void botonInsertarNuevoPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInsertarNuevoPMouseClicked

        PanelInsertarProducto nuevoProductoP = new PanelInsertarProducto();
        nuevoProductoP.setSize(820, 600);
        nuevoProductoP.setLocation(0, 0);
        panelTareas.removeAll();
        panelTareas.add(nuevoProductoP,BorderLayout.CENTER);
        panelTareas.revalidate();
        panelTareas.repaint();
    }//GEN-LAST:event_botonInsertarNuevoPMouseClicked
/**
 * Método para eliminar un producto que no este en un envio.
 * @param evt 
 */
    private void botonEliminarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarProductoMouseClicked
        
        GestionProductos gestionEliminado = new GestionProductos();
        String idProductoE = String.valueOf(tablaProductos.getValueAt
        (tablaProductos.getSelectedRow(), 0));
        if(!gestionEliminado.consularProductosEnvios(idProductoE)){
        if(gestionEliminado.eliminarProducto(idProductoE)){
            JOptionPane.showMessageDialog(this, "PRODUCTO ELIMINADO");
        }else{
            JOptionPane.showMessageDialog(this, "EL PRODUCTO "
                    + "NO SE HA PODIDO ELIMINAR");
        }
        }else{
            JOptionPane.showMessageDialog(this, "EL PRODUCTO NO SE PUEDE ELIMINAR PORQUE ESTA DENTRO DE UN ENVIO.");
        }
    }//GEN-LAST:event_botonEliminarProductoMouseClicked
/**
 * Método para modificar un producto.
 * @param evt 
 */
    private void botonModificarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonModificarProductoMouseClicked
       
        GestionProductos gestionModificado = new GestionProductos();
        if(gestionModificado.modificarProducto(productoAModificar())){
            JOptionPane.showMessageDialog(this, "EL PRODUCTO"
                    + "HA SIDO MODIFICADO CON ÉXITO");
        }else{
            JOptionPane.showMessageDialog(this, "EL PRODUCTO"
                    + " NO HA SIDO MODIFICADO");
        }
    }//GEN-LAST:event_botonModificarProductoMouseClicked
/**
 * Método par buscar un producto dentro de la tabla.
 * @param evt 
 */
    private void botonBuscarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarProductoMouseClicked
        
        GestionProductos gestionBuscado = new GestionProductos();
        GestionTablas tablas = new GestionTablas();
        List<Producto>listaEncontrados = new ArrayList<Producto>();
        try {
            listaEncontrados = gestionBuscado.buscarProducto(tfBuscarProducto.getText());
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(PanelProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        tablaProductos.setModel(tablas.crearTablaProductos(listaEncontrados));
    }//GEN-LAST:event_botonBuscarProductoMouseClicked
/**
 * Método para ir al panel de las categorias.
 * @param evt 
 */
    private void botonVerCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerCategoriasMouseClicked
        GestionCategorias gestionarCategoria = new GestionCategorias();
        
        PanelInsertarCategoria panelInsertarCategoria = new PanelInsertarCategoria();
        panelInsertarCategoria.setSize(860, 600);
        panelInsertarCategoria.setLocation(0, 0);
        panelTareas.removeAll();
        panelTareas.add(panelInsertarCategoria,BorderLayout.CENTER);
        panelTareas.revalidate();
        panelTareas.repaint();
    }//GEN-LAST:event_botonVerCategoriasMouseClicked
/**
 * Método para modificar los datos de un producto.
 * @return Devuelve verdadero si se ha modificado el producto.
 */
    private Producto productoAModificar(){
        int indice = tablaProductos.getSelectedRow();
        String idProducto = String.valueOf(tablaProductos.getValueAt(indice, 0));
        String nombre= String.valueOf(tablaProductos.getValueAt(indice, 1));
        String descripcion = String.valueOf(tablaProductos.getValueAt(indice, 2));
        //double precio = (double)String.valueOf(tablaProductos.getValueAt(indice, 3));
        double precio=Double.parseDouble(String.valueOf(tablaProductos.getValueAt(indice, 3)));
        String tipo = String.valueOf(tablaProductos.getValueAt(indice, 4));
        int disponibilidad = Integer.parseInt(String.valueOf(tablaProductos.getValueAt(indice, 5)));
        String idCategoria = String.valueOf(tablaProductos.getValueAt(indice, 6));
        Producto productoModificado = new Producto(idProducto,nombre,descripcion
        ,precio,tipo,disponibilidad,idCategoria);
        return productoModificado;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonBuscarProducto;
    private javax.swing.JLabel botonEliminarProducto;
    private javax.swing.JLabel botonInsertarNuevoP;
    private javax.swing.JLabel botonModificarProducto;
    private javax.swing.JLabel botonVerCategorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelBotonBuscarP;
    private javax.swing.JPanel panelBotonEliminarP;
    private javax.swing.JPanel panelBotonInsertarNuevoP;
    private javax.swing.JPanel panelBotonModificarP;
    private javax.swing.JPanel panelVerCategorias;
    private javax.swing.JScrollPane spTablaProductos;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField tfBuscarProducto;
    // End of variables declaration//GEN-END:variables
}
