/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventana;

import Gestion.GestionAdministrador;
import Gestion.GestionEnvios;
import Gestion.GestionProductos;
import Modelo.Administrador;
import Modelo.DetallesEnvio;
import Modelo.Envio;
import Modelo.Producto;
import com.google.gson.JsonSyntaxException;
import java.io.UnsupportedEncodingException;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jose Miguel
 */
public class PanelInsertarEnvio extends javax.swing.JPanel {

    /**
     * Creates new form PanelInsertarProducto
     */
    public PanelInsertarEnvio() {
        initComponents(); 
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitularEnvio = new javax.swing.JLabel();
        lTituloNuevoEnvio = new javax.swing.JLabel();
        tfIdEnvio = new javax.swing.JTextField();
        lIdEnvio = new javax.swing.JLabel();
        lFechaEnvio = new javax.swing.JLabel();
        tfTitularEnvio = new javax.swing.JTextField();
        tfDireccionEnvio = new javax.swing.JTextField();
        lDireccionEnvio = new javax.swing.JLabel();
        tfFechaEnvio = new javax.swing.JTextField();
        panelBotonInsertarE = new javax.swing.JPanel();
        botonInsertarEnvio = new javax.swing.JLabel();
        panelDetallesEnvio = new javax.swing.JPanel();
        lIdProducto = new javax.swing.JLabel();
        lTipoProducto = new javax.swing.JLabel();
        lDisponibilidadProducto = new javax.swing.JLabel();
        tfDisponibilidadProducto = new javax.swing.JTextField();
        tfIdProducto = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTitularEnvio.setText("Inserta el nombre del titular:");
        add(lTitularEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 250, 40));

        lTituloNuevoEnvio.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lTituloNuevoEnvio.setForeground(new java.awt.Color(60, 89, 221));
        lTituloNuevoEnvio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTituloNuevoEnvio.setText("Insertar un nuevo envio");
        add(lTituloNuevoEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 60));
        add(tfIdEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 250, 40));

        lIdEnvio.setText("Inserta el id del envio:");
        add(lIdEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 250, 40));

        lFechaEnvio.setText("Inserta la fecha del envio:");
        add(lFechaEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 250, 40));
        add(tfTitularEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 250, 40));
        add(tfDireccionEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 250, 40));

        lDireccionEnvio.setText("Inserta la direccion del envio:");
        add(lDireccionEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 250, 40));
        add(tfFechaEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 250, 40));

        panelBotonInsertarE.setBackground(new java.awt.Color(255, 255, 255));

        botonInsertarEnvio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonInsertarEnvio.setForeground(new java.awt.Color(60, 89, 221));
        botonInsertarEnvio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonInsertarEnvio.setText("Insertar");
        botonInsertarEnvio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInsertarEnvioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBotonInsertarELayout = new javax.swing.GroupLayout(panelBotonInsertarE);
        panelBotonInsertarE.setLayout(panelBotonInsertarELayout);
        panelBotonInsertarELayout.setHorizontalGroup(
            panelBotonInsertarELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonInsertarEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelBotonInsertarELayout.setVerticalGroup(
            panelBotonInsertarELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonInsertarEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(panelBotonInsertarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, 130, 40));

        panelDetallesEnvio.setBackground(new java.awt.Color(60, 89, 221));
        panelDetallesEnvio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lIdProducto.setText("Inserta el id del producto a enviar:");
        panelDetallesEnvio.add(lIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 250, 40));

        lTipoProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTipoProducto.setText("Inserta el estado del envio:");
        panelDetallesEnvio.add(lTipoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 130));

        lDisponibilidadProducto.setText("Inserta la cantidad de producto a enviar:");
        panelDetallesEnvio.add(lDisponibilidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 250, 40));
        panelDetallesEnvio.add(tfDisponibilidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 250, 40));
        panelDetallesEnvio.add(tfIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 250, 40));

        add(panelDetallesEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 300, 470));
    }// </editor-fold>//GEN-END:initComponents
/**
 * Método para insertar un nuevo envio.
 * @param evt 
 */
    private void botonInsertarEnvioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInsertarEnvioMouseClicked
        try {
            boolean envioInsertado, detallesInsertados, cantidadModificada;
            GestionEnvios gestionarEnvios = new GestionEnvios();
            int disponibilidad = obtenerDisponibilidadProducto();
            envioInsertado = gestionarEnvios.insertarEnvio(obtenerDatosEnvio());
            detallesInsertados = gestionarEnvios.insertarDetallesEnvio(obtenerDatosDetalles());
            cantidadModificada = modificarProductoEnviado(
                    tfIdProducto.getText()
                    ,disponibilidad - Integer.parseInt(tfDisponibilidadProducto.getText()));
            if(envioInsertado && detallesInsertados && cantidadModificada){
                JOptionPane.showMessageDialog(this, "ENVIO INSERTADO");
            }else{
                JOptionPane.showMessageDialog(this, "NO SE HA PODIDO"
                        + "INSERTAR EL ENVIO"
                        + "INTENTALO OTRA VEZ");
            }
           
        } 
         catch (JsonSyntaxException errorDatos) {
               JOptionPane.showMessageDialog(this, "PROBLEMA CON LOS"
                       + "DATOS INTRODUCIDOS");
        }catch (Exception e) {
               JOptionPane.showMessageDialog(this, "Error:"+ e.getMessage());
        }
       
    }//GEN-LAST:event_botonInsertarEnvioMouseClicked
/**
 * Método para obtener los datos del envio que se quiere insertar.
 * @return Devuelve un objeto de la clase Envio.
 */
    private Envio obtenerDatosEnvio(){
        Envio nuevoEnvio = null;
        String idEnvio = tfIdEnvio.getText();
        String titularEnvio = tfTitularEnvio.getText();
        String fechaEnvio = tfFechaEnvio.getText();
        String direccionEnvio = tfDireccionEnvio.getText();
        String correo = obtenerCorreoAdministrador();
        nuevoEnvio = new Envio(idEnvio,titularEnvio,fechaEnvio
                ,direccionEnvio,"preparado",correo);
        System.out.print(nuevoEnvio.toString());
        return nuevoEnvio;
    }
    /**
     * Método para obtener los datos de los detelles de un envio que se quiere insertar.
     * @return Devuelve un objeto de la clase DetallesEnvio.
     */
       private DetallesEnvio obtenerDatosDetalles(){
        DetallesEnvio nuevoDetalles = null;
        String idProducto = tfIdProducto.getText();
        String idEnvio = tfIdEnvio.getText();
        String idDetalles = idEnvio + "Detalles";
        int cantidad = Integer.parseInt(tfDisponibilidadProducto.getText());
        nuevoDetalles = new DetallesEnvio(idDetalles,idProducto,idEnvio,cantidad);
        System.out.print(nuevoDetalles.toString());
        return nuevoDetalles;
    }
       /**
        * Método para obtener el correo del admiistrador que realiza el envio.
        * @return evuelve el correo del administrador.
        */
    public String obtenerCorreoAdministrador(){
        GestionAdministrador gestionAdmin = new GestionAdministrador();
            List<Administrador> listaAdmin = gestionAdmin.obtenerAdministradorConectado();
            String correo="";
            for(Administrador admin: listaAdmin){
                correo = admin.getCorreo();
            }
       return correo;
    }
    /**
     * Método para obtener la cantidad de un producto para ver si se puede enviar.
     * @return Devuelve la disponibilidad de un porducto.
     */
     private int obtenerDisponibilidadProducto(){
         int disponibilidad = 0;
        try {
            GestionProductos gestionarProductos =  new GestionProductos();
            List<Producto> listaProductos = gestionarProductos.buscarCantidad(tfIdProducto.getText());
            for(Producto producto: listaProductos){
                disponibilidad = producto.getDisponibilidad();
            }
           
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(PanelInsertarEnvio.class.getName()).log(Level.SEVERE, null, ex);
        }
         return disponibilidad;
     }
     /**
      * Método para modificar la cantidad de los productos que hay de ese tipo.
      * @param idProducto Id del producto que se quiere modificar.
      * @param cantidad Cantidad del producto que se utiliza en el envio.
      * @return Devuelve verdadero si de modifica la cantidad del producto.
      */
    private boolean modificarProductoEnviado(String idProducto, int cantidad){
    
        boolean modificado = false;
        GestionProductos gestionarProductos =  new GestionProductos();
        modificado = gestionarProductos.modificarCantidadProducto(idProducto,cantidad);
       return modificado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonInsertarEnvio;
    private javax.swing.JLabel lDireccionEnvio;
    private javax.swing.JLabel lDisponibilidadProducto;
    private javax.swing.JLabel lFechaEnvio;
    private javax.swing.JLabel lIdEnvio;
    private javax.swing.JLabel lIdProducto;
    private javax.swing.JLabel lTipoProducto;
    private javax.swing.JLabel lTitularEnvio;
    private javax.swing.JLabel lTituloNuevoEnvio;
    private javax.swing.JPanel panelBotonInsertarE;
    private javax.swing.JPanel panelDetallesEnvio;
    private javax.swing.JTextField tfDireccionEnvio;
    private javax.swing.JTextField tfDisponibilidadProducto;
    private javax.swing.JTextField tfFechaEnvio;
    private javax.swing.JTextField tfIdEnvio;
    private javax.swing.JTextField tfIdProducto;
    private javax.swing.JTextField tfTitularEnvio;
    // End of variables declaration//GEN-END:variables
}
