/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventana;

import Gestion.GestionProductos;
import Modelo.Producto;
import com.google.gson.JsonSyntaxException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Miguel
 */
public class PanelInsertarProducto extends javax.swing.JPanel {

    /**
     * Creates new form PanelInsertarProducto
     */
    public PanelInsertarProducto() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNombreProducto = new javax.swing.JLabel();
        lTituloNuevoProducto = new javax.swing.JLabel();
        tfIdProducto = new javax.swing.JTextField();
        lIdProducto = new javax.swing.JLabel();
        lDescripcionProducto = new javax.swing.JLabel();
        tfNombreProducto = new javax.swing.JTextField();
        tfPrecioProducto = new javax.swing.JTextField();
        lPrecioProducto = new javax.swing.JLabel();
        lTipoProducto = new javax.swing.JLabel();
        lCategoriaProducto = new javax.swing.JLabel();
        tfCategoriaProducto = new javax.swing.JTextField();
        spDescripcionProducto = new javax.swing.JScrollPane();
        taDescripcionProducto = new javax.swing.JTextArea();
        rbNuevo = new javax.swing.JRadioButton();
        rbSeminuevo = new javax.swing.JRadioButton();
        rbReparado = new javax.swing.JRadioButton();
        panelBotonInsertarP = new javax.swing.JPanel();
        botonInsertarP = new javax.swing.JLabel();
        lDisponibilidadProducto = new javax.swing.JLabel();
        tfDisponibilidadProducto = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lNombreProducto.setText("Inserta el nombre del producto:");
        add(lNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 250, 40));

        lTituloNuevoProducto.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lTituloNuevoProducto.setForeground(new java.awt.Color(60, 89, 221));
        lTituloNuevoProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTituloNuevoProducto.setText("Insertar un nuevo producto");
        add(lTituloNuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 70));
        add(tfIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 250, 40));

        lIdProducto.setText("Inserta el id del producto:");
        add(lIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 250, 40));

        lDescripcionProducto.setText("Inserta una pequeña descripcion:");
        add(lDescripcionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 250, 40));
        add(tfNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 250, 40));
        add(tfPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 250, 40));

        lPrecioProducto.setText("Inserta el precio del producto:");
        add(lPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 250, 40));

        lTipoProducto.setText("Inserta el tipo del produto:");
        add(lTipoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 250, 40));

        lCategoriaProducto.setText("Inserta la categoria a la que pertenece:");
        add(lCategoriaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 250, 40));
        add(tfCategoriaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 250, 40));

        taDescripcionProducto.setColumns(20);
        taDescripcionProducto.setRows(5);
        spDescripcionProducto.setViewportView(taDescripcionProducto);

        add(spDescripcionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 520, 160));

        rbNuevo.setText("Nuevo");
        add(rbNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));

        rbSeminuevo.setText("Seminuevo");
        add(rbSeminuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        rbReparado.setText("Reparado");
        add(rbReparado, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, -1));

        panelBotonInsertarP.setBackground(new java.awt.Color(255, 255, 255));

        botonInsertarP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonInsertarP.setForeground(new java.awt.Color(60, 89, 221));
        botonInsertarP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonInsertarP.setText("Insertar");
        botonInsertarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInsertarPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBotonInsertarPLayout = new javax.swing.GroupLayout(panelBotonInsertarP);
        panelBotonInsertarP.setLayout(panelBotonInsertarPLayout);
        panelBotonInsertarPLayout.setHorizontalGroup(
            panelBotonInsertarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonInsertarP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelBotonInsertarPLayout.setVerticalGroup(
            panelBotonInsertarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonInsertarP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(panelBotonInsertarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, 130, 40));

        lDisponibilidadProducto.setText("Inserta el número de porductos totales:");
        add(lDisponibilidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 250, 40));
        add(tfDisponibilidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 250, 40));
    }// </editor-fold>//GEN-END:initComponents
/**
 * Método para insertar un nuevo producto.
 * @param evt 
 */
    private void botonInsertarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInsertarPMouseClicked
        try{
        GestionProductos gestionProducto = new GestionProductos();
        String idProducto = tfIdProducto.getText();
        String nombre = tfNombreProducto.getText();
        String descripcion = taDescripcionProducto.getText();
        double precio = Double.parseDouble(tfPrecioProducto.getText());
        String tipo = obtenerTipoProducto();
        int disponibilidad = Integer.parseInt(tfDisponibilidadProducto.getText());
        String categoriaid = tfCategoriaProducto.getText() ;
        Producto nuevoProducto = new Producto(idProducto,nombre,descripcion
        ,precio,tipo,disponibilidad,categoriaid);
       if(gestionProducto.insertarProducto(nuevoProducto)){
           JOptionPane.showMessageDialog(this, "Producto insertado con éxito");
       }
        }catch(JsonSyntaxException errorJson){
            JOptionPane.showMessageDialog(this,"ERROR");
        }catch(NumberFormatException e ){
            JOptionPane.showMessageDialog(this, "ERROR: TIENE QUE SER UN NUMERO");
        }
        
        catch(Exception e ){
            JOptionPane.showMessageDialog(this, "ERROR:"+ e.getMessage());
        }
        
    }//GEN-LAST:event_botonInsertarPMouseClicked
/**
 * Método para obtener el radioButton marcado.
 * @return Devuelve una cadena según el radioButton marcado.
 */
    private String obtenerTipoProducto(){
        String resultado = "";
        if(rbNuevo.isSelected()){
            resultado = "nuevo";
        }if(rbSeminuevo.isSelected()){
            resultado = "seminuevo";
        }if(rbReparado.isSelected()){
            resultado = "reparado";
        }
       
        return resultado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonInsertarP;
    private javax.swing.JLabel lCategoriaProducto;
    private javax.swing.JLabel lDescripcionProducto;
    private javax.swing.JLabel lDisponibilidadProducto;
    private javax.swing.JLabel lIdProducto;
    private javax.swing.JLabel lNombreProducto;
    private javax.swing.JLabel lPrecioProducto;
    private javax.swing.JLabel lTipoProducto;
    private javax.swing.JLabel lTituloNuevoProducto;
    private javax.swing.JPanel panelBotonInsertarP;
    private javax.swing.JRadioButton rbNuevo;
    private javax.swing.JRadioButton rbReparado;
    private javax.swing.JRadioButton rbSeminuevo;
    private javax.swing.JScrollPane spDescripcionProducto;
    private javax.swing.JTextArea taDescripcionProducto;
    private javax.swing.JTextField tfCategoriaProducto;
    private javax.swing.JTextField tfDisponibilidadProducto;
    private javax.swing.JTextField tfIdProducto;
    private javax.swing.JTextField tfNombreProducto;
    private javax.swing.JTextField tfPrecioProducto;
    // End of variables declaration//GEN-END:variables
}
