/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventana;


import Gestion.GestionEnvios;
import Gestion.GestionFacturas;
import Modelo.Factura;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Miguel
 */
public class PanelInsertarFactura extends javax.swing.JPanel {

    /**
     * Creates new form PanelInsertarProducto
     */
    public PanelInsertarFactura() {
        initComponents(); 
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitularFactura = new javax.swing.JLabel();
        lTituloNuevoEnvio = new javax.swing.JLabel();
        tfIdFactura = new javax.swing.JTextField();
        lIdFactura = new javax.swing.JLabel();
        lTotalPagado = new javax.swing.JLabel();
        tfTitularFactura = new javax.swing.JTextField();
        tfDescuento = new javax.swing.JTextField();
        lDescuento = new javax.swing.JLabel();
        tfTotalPagado = new javax.swing.JTextField();
        panelBotonInsertarF = new javax.swing.JPanel();
        botonInsertarFactura = new javax.swing.JLabel();
        lIdEnvio = new javax.swing.JLabel();
        tfIdEnvio = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTitularFactura.setText("Inserta el nombre del titular:");
        add(lTitularFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 250, 40));

        lTituloNuevoEnvio.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lTituloNuevoEnvio.setForeground(new java.awt.Color(60, 89, 221));
        lTituloNuevoEnvio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTituloNuevoEnvio.setText("Insertar un nuevo envio");
        add(lTituloNuevoEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 60));
        add(tfIdFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 250, 40));

        lIdFactura.setText("Inserta el id de la factura");
        add(lIdFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 250, 40));

        lTotalPagado.setText("Inserta el total del envio:");
        add(lTotalPagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 250, 40));
        add(tfTitularFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 250, 40));
        add(tfDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 250, 40));

        lDescuento.setText("Inserta el descuento:");
        add(lDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 250, 40));
        add(tfTotalPagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 250, 40));

        panelBotonInsertarF.setBackground(new java.awt.Color(255, 255, 255));

        botonInsertarFactura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonInsertarFactura.setForeground(new java.awt.Color(60, 89, 221));
        botonInsertarFactura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonInsertarFactura.setText("Insertar");
        botonInsertarFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInsertarFacturaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBotonInsertarFLayout = new javax.swing.GroupLayout(panelBotonInsertarF);
        panelBotonInsertarF.setLayout(panelBotonInsertarFLayout);
        panelBotonInsertarFLayout.setHorizontalGroup(
            panelBotonInsertarFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonInsertarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelBotonInsertarFLayout.setVerticalGroup(
            panelBotonInsertarFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonInsertarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(panelBotonInsertarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, 130, 40));

        lIdEnvio.setText("Inserta el id del envio:");
        add(lIdEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 250, 40));
        add(tfIdEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 250, 40));
    }// </editor-fold>//GEN-END:initComponents
/**
 * Método para insertar un factura.
 * @param evt 
 */
    private void botonInsertarFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInsertarFacturaMouseClicked
        try {
            boolean facturaInsertada = false;
           GestionFacturas gestionarFacturas = new GestionFacturas();
           System.out.print(obtenerDatosFactura().toString());
           facturaInsertada = gestionarFacturas.insertarFactura(obtenerDatosFactura());
           System.out.print(facturaInsertada);
            if(facturaInsertada && cambiarEstadoEnvio()){
                JOptionPane.showMessageDialog(this, "FACTURA INSERTADA"
                + "Y ENVIO ENVIADO");
            }else{
                JOptionPane.showMessageDialog(this, "NO SE HA PODIDO"
                        + "INSERTAR LA FACTURA"
                        + "INTENTALO OTRA VEZ");
            }
        }
        catch (Exception e) {
               JOptionPane.showMessageDialog(this, "Error:"+ e.getMessage());
        }
       
    }//GEN-LAST:event_botonInsertarFacturaMouseClicked
/**
 * Método para obtener los datos de la factura que se quiere insertar.
 * @return 
 */
    private Factura obtenerDatosFactura(){
        Factura nuevaFactura = null;
        String idFactura = tfIdFactura.getText();
        String titularFactura = tfTitularFactura.getText();
        double totalPagado = Double.parseDouble(tfTotalPagado.getText());
        int descuento = Integer.parseInt(tfDescuento.getText());
        
        String idEnvio = tfIdEnvio.getText();
        nuevaFactura = new Factura(idFactura,titularFactura,totalPagado,
        descuento,idEnvio); 
        return nuevaFactura;
    }
    /**
     * Método para cambiar el estado de un envio una vez que se realiza su factura.
     * @return Devuelve verdadero si se cambia el estado del envio.
     */
    private boolean cambiarEstadoEnvio(){
        boolean cambiado = false;
        GestionEnvios gestionarEnvio = new GestionEnvios();
        String idEnvio = tfIdEnvio.getText();
        cambiado = gestionarEnvio.modificarEnvio(idEnvio, "enviado");
        return cambiado;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonInsertarFactura;
    private javax.swing.JLabel lDescuento;
    private javax.swing.JLabel lIdEnvio;
    private javax.swing.JLabel lIdFactura;
    private javax.swing.JLabel lTitularFactura;
    private javax.swing.JLabel lTituloNuevoEnvio;
    private javax.swing.JLabel lTotalPagado;
    private javax.swing.JPanel panelBotonInsertarF;
    private javax.swing.JTextField tfDescuento;
    private javax.swing.JTextField tfIdEnvio;
    private javax.swing.JTextField tfIdFactura;
    private javax.swing.JTextField tfTitularFactura;
    private javax.swing.JTextField tfTotalPagado;
    // End of variables declaration//GEN-END:variables
}
