/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Gestion.GestionAdministrador;
import Modelo.Administrador;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Jose Miguel
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInventario = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        panelBotonProductos = new javax.swing.JPanel();
        botonProductos = new javax.swing.JLabel();
        panelBotonSalir = new javax.swing.JPanel();
        botonSalir = new javax.swing.JLabel();
        panelBotonEnvios = new javax.swing.JPanel();
        botonEnvios = new javax.swing.JLabel();
        panelBotonFacturas = new javax.swing.JPanel();
        botonFacturas = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tituloTuinventario = new javax.swing.JLabel();
        panelBotonCerrar = new javax.swing.JPanel();
        botonCerrarSesion = new javax.swing.JLabel();
        panelTareas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelInventario.setBackground(new java.awt.Color(255, 255, 255));
        panelInventario.setMinimumSize(new java.awt.Dimension(1200, 600));
        panelInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(60, 89, 221));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBotonProductos.setOpaque(false);
        panelBotonProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonProductos.setForeground(new java.awt.Color(255, 255, 255));
        botonProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonProductos.setText("Productos");
        botonProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonProductosMouseClicked(evt);
            }
        });
        panelBotonProductos.add(botonProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 70));

        panelMenu.add(panelBotonProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 340, 70));

        panelBotonSalir.setOpaque(false);
        panelBotonSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonSalir.setText("Cerrar sesion y salir");
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
        });
        panelBotonSalir.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 70));

        panelMenu.add(panelBotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 340, 70));

        panelBotonEnvios.setOpaque(false);
        panelBotonEnvios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonEnvios.setForeground(new java.awt.Color(255, 255, 255));
        botonEnvios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonEnvios.setText("Envios");
        botonEnvios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEnviosMouseClicked(evt);
            }
        });
        panelBotonEnvios.add(botonEnvios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 70));

        panelMenu.add(panelBotonEnvios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 340, 70));

        panelBotonFacturas.setOpaque(false);
        panelBotonFacturas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonFacturas.setForeground(new java.awt.Color(255, 255, 255));
        botonFacturas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonFacturas.setText("Facturas");
        botonFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonFacturasMouseClicked(evt);
            }
        });
        panelBotonFacturas.add(botonFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 70));

        panelMenu.add(panelBotonFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 340, 70));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloTuinventario.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tituloTuinventario.setForeground(new java.awt.Color(255, 255, 255));
        tituloTuinventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloTuinventario.setText("TU INVENTARIO");
        tituloTuinventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tituloTuinventarioMouseClicked(evt);
            }
        });
        jPanel1.add(tituloTuinventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 120));

        panelMenu.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 120));

        panelBotonCerrar.setBackground(new java.awt.Color(60, 89, 221));
        panelBotonCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        botonCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonCerrarSesion.setText("Cerrar Sesion");
        botonCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCerrarSesionMouseClicked(evt);
            }
        });
        panelBotonCerrar.add(botonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 40));

        panelMenu.add(panelBotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 340, 40));

        panelInventario.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 600));

        panelTareas.setOpaque(false);

        javax.swing.GroupLayout panelTareasLayout = new javax.swing.GroupLayout(panelTareas);
        panelTareas.setLayout(panelTareasLayout);
        panelTareasLayout.setHorizontalGroup(
            panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        panelTareasLayout.setVerticalGroup(
            panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        panelInventario.add(panelTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 860, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Método para vover a la pantalla principal.
 * @param evt 
 */
    private void tituloTuinventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloTuinventarioMouseClicked
        PanelInicio panelInicio = new PanelInicio();
        panelInicio.setSize(860, 600);
        panelInicio.setLocation(0, 0);
        panelTareas.removeAll();
        panelTareas.add(panelInicio,BorderLayout.CENTER);
        panelTareas.revalidate();
        panelTareas.repaint();
    }//GEN-LAST:event_tituloTuinventarioMouseClicked
/**
 * Método para ir al panel de los productos.
 * @param evt 
 */
    private void botonProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProductosMouseClicked

        PanelProductos panelProductos = new PanelProductos();
        panelProductos.setSize(860, 600);
        panelProductos.setLocation(0, 0);
        panelTareas.removeAll();
        panelTareas.add(panelProductos,BorderLayout.CENTER);
        panelTareas.revalidate();
        panelTareas.repaint();
    }//GEN-LAST:event_botonProductosMouseClicked
/**
 * Método para ir al panel de los envios.
 * @param evt 
 */
    private void botonEnviosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEnviosMouseClicked
        
        PanelEnvios panelEnvios = new PanelEnvios();
        panelEnvios.setSize(860, 600);
        panelEnvios.setLocation(0, 0);
        panelTareas.removeAll();
        panelTareas.add(panelEnvios,BorderLayout.CENTER);
        panelTareas.revalidate();
        panelTareas.repaint();
    }//GEN-LAST:event_botonEnviosMouseClicked
/**
 * Métoodo para cerrar sesion.
 * @param evt 
 */
    private void botonCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarSesionMouseClicked
        
            VentanaLogin volverLogin = new VentanaLogin();
            GestionAdministrador gestionAdmin = new GestionAdministrador();
            List<Administrador> listaAdmin = new ArrayList<Administrador>();
            listaAdmin = gestionAdmin.obtenerAdministradorConectado();
            Administrador adminDesconectado = null;
            for(Administrador admin: listaAdmin){
               adminDesconectado = new Administrador(admin.getCorreo()
                       ,admin.getContrasena(),0);
            }
            if(gestionAdmin.modificarAdministradorConectado(adminDesconectado)){
                volverLogin.setVisible(true);
                dispose();
            }
       
    }//GEN-LAST:event_botonCerrarSesionMouseClicked
/**
 * Método para ir la panel de facturas.
 * @param evt 
 */
    private void botonFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonFacturasMouseClicked
        PanelInsertarFactura panelIFactura = new PanelInsertarFactura();
        panelIFactura.setSize(860, 600);
        panelIFactura.setLocation(0, 0);
        panelTareas.removeAll();
        panelTareas.add(panelIFactura,BorderLayout.CENTER);
        panelTareas.revalidate();
        panelTareas.repaint();
    }//GEN-LAST:event_botonFacturasMouseClicked
/**
 * Método para cerrar sesion y salidr de la aplicacion.
 * @param evt 
 */
    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseClicked

            GestionAdministrador gestionAdmin = new GestionAdministrador();
            List<Administrador> listaAdmin = new ArrayList<Administrador>();
            listaAdmin = gestionAdmin.obtenerAdministradorConectado();
            Administrador adminDesconectado = null;
            for(Administrador admin: listaAdmin){
               adminDesconectado = new Administrador(admin.getCorreo()
                       ,admin.getContrasena(),0);
            }
            if(gestionAdmin.modificarAdministradorConectado(adminDesconectado)){
               System.exit(0);
            }
       
    }//GEN-LAST:event_botonSalirMouseClicked

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonCerrarSesion;
    private javax.swing.JLabel botonEnvios;
    private javax.swing.JLabel botonFacturas;
    private javax.swing.JLabel botonProductos;
    private javax.swing.JLabel botonSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelBotonCerrar;
    private javax.swing.JPanel panelBotonEnvios;
    private javax.swing.JPanel panelBotonFacturas;
    private javax.swing.JPanel panelBotonProductos;
    private javax.swing.JPanel panelBotonSalir;
    private javax.swing.JPanel panelInventario;
    private javax.swing.JPanel panelMenu;
    public static javax.swing.JPanel panelTareas;
    private javax.swing.JLabel tituloTuinventario;
    // End of variables declaration//GEN-END:variables
}
