/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Gestion.GestionAdministrador;
import Gestion.ValidarDatos;
import Modelo.Administrador;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VentanaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegistro
     */
    public VentanaRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistro = new javax.swing.JPanel();
        tituloRegistro = new javax.swing.JLabel();
        tituloNuevoCorreo = new javax.swing.JLabel();
        campoCorreoR = new javax.swing.JTextField();
        campoRepetirContrasena = new javax.swing.JPasswordField();
        campoContrasenaR = new javax.swing.JPasswordField();
        tituloRepetirContrasena = new javax.swing.JLabel();
        tituloNuevaContrasena = new javax.swing.JLabel();
        panelBotonEntrarR = new javax.swing.JPanel();
        botonEntrarR = new javax.swing.JLabel();
        panelVolver = new javax.swing.JPanel();
        botonVolver = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelRegistro.setBackground(new java.awt.Color(255, 255, 255));
        panelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloRegistro.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tituloRegistro.setForeground(new java.awt.Color(60, 89, 221));
        tituloRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloRegistro.setText("Registro para nuevos administradores");
        panelRegistro.add(tituloRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 400, 50));

        tituloNuevoCorreo.setText("Introduce tu correo electrónico:");
        panelRegistro.add(tituloNuevoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 360, -1));
        panelRegistro.add(campoCorreoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 360, 40));
        panelRegistro.add(campoRepetirContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 360, 40));
        panelRegistro.add(campoContrasenaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 360, 40));

        tituloRepetirContrasena.setText("Vuelve a introducir tu contraseña:");
        panelRegistro.add(tituloRepetirContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 360, 20));

        tituloNuevaContrasena.setText("Introduce tu contraseña:");
        panelRegistro.add(tituloNuevaContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 360, 20));

        panelBotonEntrarR.setBackground(new java.awt.Color(60, 89, 221));

        botonEntrarR.setForeground(new java.awt.Color(255, 255, 255));
        botonEntrarR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonEntrarR.setText("ENTRAR");
        botonEntrarR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEntrarRMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBotonEntrarRLayout = new javax.swing.GroupLayout(panelBotonEntrarR);
        panelBotonEntrarR.setLayout(panelBotonEntrarRLayout);
        panelBotonEntrarRLayout.setHorizontalGroup(
            panelBotonEntrarRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonEntrarRLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonEntrarR, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBotonEntrarRLayout.setVerticalGroup(
            panelBotonEntrarRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonEntrarRLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonEntrarR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelRegistro.add(panelBotonEntrarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 90, 40));

        panelVolver.setBackground(new java.awt.Color(255, 255, 255));

        botonVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(60, 89, 221));
        botonVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonVolver.setText("Volver");
        botonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelVolverLayout = new javax.swing.GroupLayout(panelVolver);
        panelVolver.setLayout(panelVolverLayout);
        panelVolverLayout.setHorizontalGroup(
            panelVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        panelVolverLayout.setVerticalGroup(
            panelVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelRegistro.add(panelVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Método para entrar en la aplicacion una vez que se ha registrado correctamente.
 * @param evt 
 */
    private void botonEntrarRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEntrarRMouseClicked
  
        if(comprobarDatosCorrectos(campoCorreoR.getText()
                ,String.valueOf(campoContrasenaR.getPassword())
                ,String.valueOf(campoRepetirContrasena.getPassword())) )
                {
        Administrador adminRegistro = new Administrador(campoCorreoR.getText()
                ,String.valueOf(campoContrasenaR.getPassword()),0);
        if(comprobarCorrecto(adminRegistro)){
            VentanaLogin ventanaLogin = new VentanaLogin();
            ventanaLogin.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(this,"ERROR-LOGIN INCORRECTO.");
        
        }
        }else{
            JOptionPane.showMessageDialog(this,"ERROR- LA CONTRASEÑA NO ES VALIDA."
                    + "TIENE QUE TENER 8 O MÁS CARACTERES, DEBE INCLUIR NÚMEROS Y CARACTERES EJEMPLO:ADMIN1!1" );
        }
        
    }//GEN-LAST:event_botonEntrarRMouseClicked
/**
 * Méotodo para volver a la ventana del login.
 * @param evt 
 */
    private void botonVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVolverMouseClicked
        VentanaLogin ventanaLogin = new VentanaLogin();
        ventanaLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonVolverMouseClicked
/**
 * Méotodo para comprobar si el registro ha sido correcto.
 * @param admin Administrador que se va a comprobar.
 * @return Devuelve verdadero si los datos son correctos.
 */
    private boolean comprobarCorrecto(Administrador admin){
        GestionAdministrador nuevoAdministrador = new GestionAdministrador();
        boolean registrado = nuevoAdministrador.alta(admin);
        return registrado;
    }
    /**
     * Méotodo para comprobar si los datos del registro son correcto.
     * @param correo Correo del nuevo administrador.
     * @param contrasena Contraseña del nuevo administrador
     * @param contrasenaDos Comporbar si se introduce bien  la contraseña.
     * @return Devuelve verdadero si todos los datos son correctos.
     */
    private boolean comprobarDatosCorrectos(String correo,String contrasena, String contrasenaDos){
        boolean datosCorrectos = false;
        ValidarDatos validarAdmin = new ValidarDatos();
        if(validarAdmin.validarCorreo(correo) 
                && validarAdmin.validarContrasena(contrasena)
                && validarAdmin.validarContrasena(contrasenaDos)
                && contrasena.equals(contrasenaDos)){
            datosCorrectos = true;
        }
        return datosCorrectos;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonEntrarR;
    private javax.swing.JLabel botonVolver;
    private javax.swing.JPasswordField campoContrasenaR;
    private javax.swing.JTextField campoCorreoR;
    private javax.swing.JPasswordField campoRepetirContrasena;
    private javax.swing.JPanel panelBotonEntrarR;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JPanel panelVolver;
    private javax.swing.JLabel tituloNuevaContrasena;
    private javax.swing.JLabel tituloNuevoCorreo;
    private javax.swing.JLabel tituloRegistro;
    private javax.swing.JLabel tituloRepetirContrasena;
    // End of variables declaration//GEN-END:variables
}
